# 应用基本信息
spring:
  application:
    name: video-master
  profiles:
    # 默认激活的环境
    active: local
    # 包含的环境（可用于多环境合并）
    group:
      dev: dev
      test: test
      prod: prod
      local: local

# 服务配置
server:
  port: ${SERVER_PORT:8080}
  servlet:
    context-path: /api
  compression:
    enabled: true
    mime-types: text/html,text/xml,text/plain,text/css,application/json,application/javascript

# MyBatis Plus 基础配置（环境无关配置）
mybatis-plus:
  # 配置文件位置
#  config-location: classpath:config/mybatis-config.xml
  # mapper.xml文件位置
  mapper-locations: classpath:mapper/**/*.xml
  # 实体扫描包路径
  type-aliases-package: com.holems.master.*.entity
  # 全局配置
#  global-config:
#    db-config:
#      id-type: AUTO
#      logic-delete-field: deleted
#      logic-delete-value: 1
#      logic-not-delete-value: 0
#  configuration:
#    map-underscore-to-camel-case: true
#    cache-enabled: true
#    jdbc-type-for-null: null
