spring:
  datasource:
    url: jdbc:mysql://localhost:3306/video_master?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: root
    password: root

    # HikariCP 连接池配置（本地开发简化）
    hikari:
      pool-name: VideoMasterHikariCP-Local
      minimum-idle: 3
      maximum-pool-size: 10
      connection-timeout: 30000